[package]
name = "hello-bin"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hello-bin"
path = "./src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
assert_cmd = "2.0.13"
predicates = "3.1.0"
