on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo build --verbose --release
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: hello-bin
      #     path: target/release/hello-bin
      #     retention-days: 1
