on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo build --verbose --release
      - run: tar -cvf /tmp/target.tar target
      - uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: /tmp/taget.tar
          retention-days: 1
      # - run: cargo install --path .
      # - run: tar -cvf /tmp/hello-bin.tar ~/.cargo/bin/hello-bin
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: binary
      #     path: /tmp/hello-bin.tar
      #     retention-days: 1
