on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  install:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com
      - run: cargo install --git https://github.com/${{ github.repository }}.git --branch ${{ env.BRANCH_NAME }}
      # - run: ls -al ~/.cargo/bin
      - run: tar -cvf /tmp/hello-bin.tar ~/.cargo/bin/hello-bin
      - uses: actions/upload-artifact@v4
        with:
          name: hello-bin
          # path: ~/.cargo/bin/hello-bin
          path: /tmp/hello-bin.tar
          retention-days: 1
      # - uses: cargo-bins/cargo-binstall@main
      # - run: cargo binstall -- --git https://github.com/${{ github.repository }}.git --branch ${{ env.BRANCH_NAME }}
