on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  # test:
  #   uses: ./.github/workflows/test.yml
  # build:
  #   uses: ./.github/workflows/build.yml
  install:
    # needs: [test, build]
    uses: ./.github/workflows/install.yml
    secrets: inherit
  use:
    needs: [install]
    uses: ./.github/workflows/use.yml
