on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  test:
    needs: [build]
    uses: ./.github/workflows/test.yml
  # install:
  #   needs: [build, test]
  #   uses: ./.github/workflows/test.yml
  use:
    # needs: [build, test, install]
    needs: [build, test]
    uses: ./.github/workflows/use.yml
