on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml
  build:
    uses: ./.github/workflows/build.yml
  use:
    needs: [build]
    uses: ./.github/workflows/use.yml
