name: Main Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/rust.yml
    secrets: inherit
  install:
    needs: build
    uses: ./.github/workflows/install.yml
    secrets: inherit
