name: Build Package

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v4
      - run: cargo build --verbose -r
      - run: cargo test --no-fail-fast --verbose --all-targets
      - uses: actions/upload-artifact@v4
        with:
          name: hello-bin
          path: target/release/hello-bin
  test:
    runs-on: ubuntu-latest
    needs: build
    name: Test
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: hello-bin
      - run: ./hello-bin
      # - name: Install Package
      #   run: cargo install --path .
      # - name: Run Package
      #   run: hello-bin
