name: Rust CI

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com
      # - run: cargo build --verbose --release
      # - run: cargo test --verbose
      - run: cargo install --git https://github.com/NewEarthTech/rust-build-and-host-binary.git
      - run: hello-bin
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: hello-bin
      #     path: target/release/hello-bin
  # test:
  # runs-on: ubuntu-latest
  # needs: build
  # name: Run Package
  # steps:
  # - uses: actions/download-artifact@v4
  #   with:
  #     name: hello-bin
  # - run: ./hello-bin
