on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  use:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: binaries
          path: /tmp/
      - run: tar -xvf /tmp/target.tar
      - run: cargo install --path .
      - run: hello-bin
