name: Install

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  use:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binary
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          # path: ~/.cargo/bin/hello-bin
          path: /tmp/
      - run: tar -xvf /tmp/hello-bin.tar -C / # -C ~/.cargo/bin
      # - run: chmod +x ~/.cargo/bin/hello-bin
      - run: ls ~/.cargo/bin -al
      # - run: echo "~/.cargo/bin" >> $GITHUB_PATH
      # - run: echo "$GITHUB_PATH"
      - run: hello-bin
